name: Unit test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Ghidra
        uses: antoniovazquezblanco/setup-ghidra@v2.0.3
        with:
          version: '11.2'
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            /opt/hostedtoolcache/z3
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Download Z3
        uses: pavpanchekha/setup-z3@0.2.0
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          version: '4.8.15'
          architecture: 'x64'
          distribution: 'glibc-2.31'
      - name: Setup Environment variables if use cache
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "CPATH=/opt/hostedtoolcache/z3/4.8.15/x64/z3-4.8.15-x64-glibc-2.31/include" >> $GITHUB_ENV
      - name: Setup Z3
        run: |
          cp $CPATH/../bin/com.microsoft.z3.jar $GITHUB_WORKSPACE/lib/com.microsoft.z3.jar
          sudo cp $CPATH/../bin/*.so  /lib
      - name: Build extension
        run: gradle buildExtension --info --stacktrace
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BinAbsInspector
          path: dist/*.zip
      - name: Unit test
        run: gradle test
